feature:[프론트 검색(비 로그인)] 상단 네비게이션 레이아웃 #2
hongikbros/frontend pull request #10
Opened 2021-01-28 16:45 UTC by ja960508

기본 레이아웃 설계

header width 100% 설정

logo, link, loginbutton 각각 15%, 75%, 10% 씩 설정

header와 하위 항목들 전부 컴포넌트화(재사용성 고려)

postcss로 각 항목들 스타일링

2021-01-28 16:46 UTC, ja960508 commented
오금이 저릴 정도로 완벽하네요

2021-01-28 16:50 UTC, joseph415 commented
commit message 를 우리가 말한대로 컨벤션대로 작성하면 좋을 듯

2021-01-28 17:00 UTC, joseph415 requested changes
커밋 메시지 우리가 하기로한 컨벤션에 맞춰서 쓰면 좋을 듯
모르겠으면 내꺼보고 참고하고 다음 커밋부터는 그렇게 해주셈

2021-01-29 02:18 UTC, ja960508 commented on src/component/header/header.jsx
> +
state 있으면 class로 하고 stateless면 function으로 하는 게 정석임

근데 지금은 레이아웃만 잡으려고 일단은 class component로 만들었습니다

2021-01-29 02:20 UTC, ja960508 commented on src/component/header/navbar.jsx
> +}
그 부분도 지금은 스타일링이 많이 안 들어간 상태라 혹시 몰라서 따로 파일로 만들었습니다..

ㅠㅠ 힝...

2021-01-29 11:41 UTC, closed without merging